# Generated by Django 3.0 on 2024-12-04 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0018_auto_20200327_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 23, 24, 46, 474113), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 23, 24, 46, 474113), verbose_name='归还期限'),
        ),
    ]
