# Generated by Django 3.0 on 2024-12-04 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0019_auto_20241204_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='归还期限'),
        ),
    ]
